services:
  - type: web
    name: ai-vertex
    env: python
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      python - <<'PY'
      import os, base64, pathlib
      b64 = os.getenv("GCP_KEY_B64")
      if not b64:
        raise SystemExit("Missing env GCP_KEY_B64")
      p = pathlib.Path("/opt/render/project/src/gcp-key.json")
      p.write_bytes(base64.b64decode(b64))
      print(">> wrote", p)
      PY
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GCP_PROJECT_ID
        sync: false
      - key: GCP_LOCATION
        value: us-central1
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /opt/render/project/src/gcp-key.json
      - key: GCP_KEY_B64
        sync: false
